### ISSUE TITLE
image構文の中で改行を2つ入れると壊れる

### ISSUE THREAD

**Issue by anchan828** [vvakame/review.js#14]
動作には影響ないのですが報告しておきます！
題目の通りで、以下のように改行を2つ入れると ```{ //}``` が残ってしまいます。

```
//image[ss01][これらは全てマウスで操作できる]{


//}
```

![](https://dl.dropboxusercontent.com/u/153254465/screenshot2/ss%202015-08-11%2021.50.49.png)

**Comment by anchan828** [comment]
language-review のバージョンは 0.8.10 です

**Comment by vvakame** [comment]
review.js側のバグかな…？

**Comment by vvakame** [comment]
なおしたー！なおしたよー！ありがとー！
