### ISSUE TITLE
プレビューの自動ビルドをファイル保存時のみにしたい

### ISSUE THREAD

**Issue by anchan828** [vvakame/review.js#15]
PDFにすると30ページ位になる量の re ファイルを扱っていると、プレビューのビルドが走るごとに重くなってしまいます。

ファイル保存時のみビルドを走らせるトリガーなどあるのでしょうか？

**Comment by vvakame** [comment]
ないかも…。オプションでそういう設定を設けたほうがいいかな…。
なお、次回リリースでビルド自体がわりと早くなるかも…。なるといいな…。

**Comment by anchan828** [comment]
> ないかも…。オプションでそういう設定を設けたほうがいいかな…。
高負荷な処理であれば、処理タイミングを選べるオブションはないよりはあったほうがいいかも？

> なお、次回リリースでビルド自体がわりと早くなるかも…。なるといいな…。
了解ですー。まずはバージョンアップ後にどうなっているか確認してみます！

**Comment by vvakame** [comment]
https://twitter.com/vvakame/status/631826825543479296
というわけで割りと体感できる程度に速度が早くなったバージョンをreview.js、language-reviewともに追加した。
満足できそうなほど改善されたらCloseしてたもれ。

**Comment by anchan828** [comment]
ありがとうございます！明日ガッツリ作業予定なのでその時評価しますー。

**Comment by anchan828** [comment]
1000行で10秒くらいかかってたビルド時間が3秒くらいになりました！
これなら問題なさそうです。

**Comment by vvakame** [comment]
ｳｯそれでも3秒か… がんばろう
