### ISSUE TITLE
囲み記事のブロック命令が機能せず、非対応として表示される。

### ISSUE THREAD

**Issue by TakamiChie** [vvakame/review.js#37]
atsushieno氏作の拡張「vscode-language-review」でエラーを報告したところ、こちらでの報告も紹介されたため、あらためて報告致します。
* 元の内容 [Block instructions for enclosed articles do not work and are displayed as non\-compliant\. · Issue \#22 · atsushieno/vscode\-language\-review](https://github.com/atsushieno/vscode-language-review/issues/22)

# 問題
noteコマンドがサポートされておらず、noteコマンドが含まれるreファイルを読み込むと、次のメッセージが表示されます。
```
note というブロック構文はサポートされていません。
```

ただし、本家Re:view ではnoteコマンドはサポートされているため、次のコマンドがエラーにならず、HTML が出力されます。

```
> review compile --target html ch-01.re
```

# 期待される動作
"//note" コマンドがエラーとならないこと。

# 周辺確認
次のコマンドも同様にエラーとして表示されました。

*//memo
*//tip
*//info
*//warning
*//important
*//caution
*//notice

また、各コマンドキャプションの指定が可能ですが、キャプションを指定しても、省略しても、エラーになります。

# 参照仕様
Re:VIEW フォーマットガイド>囲み記事
https://github.com/kmuto/review/blob/master/doc/format.ja.md#%E5%9B%B2%E3%81%BF%E8%A8%98%E4%BA%8B

# バージョン
* PC: Windows 10 Home Ver 1809 ビルド17763.316

**Comment by vvakame** [comment]
たかはしさんありがとうございました…！
